// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/zk.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/zk.proto</summary>
public static partial class ZkReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/zk.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ZkReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5wcm90by96ay5wcm90byJtCgZTZXJ2ZXISFAoMem1xX3RjcF9wb3J0GAEg",
          "ASgJEgwKBGhvc3QYAiABKAkSEwoLdG90YWxfc3BhY2UYAyABKAQSFwoPYXZh",
          "aWxhYmxlX3NwYWNlGAQgASgEEhEKCWh0dHBfcG9ydBgFIAEoCWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Server), global::Server.Parser, new[]{ "ZmqTcpPort", "Host", "TotalSpace", "AvailableSpace", "HttpPort" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Server : pb::IMessage<Server> {
  private static readonly pb::MessageParser<Server> _parser = new pb::MessageParser<Server>(() => new Server());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Server> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ZkReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Server() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Server(Server other) : this() {
    zmqTcpPort_ = other.zmqTcpPort_;
    host_ = other.host_;
    totalSpace_ = other.totalSpace_;
    availableSpace_ = other.availableSpace_;
    httpPort_ = other.httpPort_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Server Clone() {
    return new Server(this);
  }

  /// <summary>Field number for the "zmq_tcp_port" field.</summary>
  public const int ZmqTcpPortFieldNumber = 1;
  private string zmqTcpPort_ = "";
  /// <summary>
  /// addr for zmq
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ZmqTcpPort {
    get { return zmqTcpPort_; }
    set {
      zmqTcpPort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "host" field.</summary>
  public const int HostFieldNumber = 2;
  private string host_ = "";
  /// <summary>
  /// host for zmq
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Host {
    get { return host_; }
    set {
      host_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "total_space" field.</summary>
  public const int TotalSpaceFieldNumber = 3;
  private ulong totalSpace_;
  /// <summary>
  /// data for disk space
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong TotalSpace {
    get { return totalSpace_; }
    set {
      totalSpace_ = value;
    }
  }

  /// <summary>Field number for the "available_space" field.</summary>
  public const int AvailableSpaceFieldNumber = 4;
  private ulong availableSpace_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong AvailableSpace {
    get { return availableSpace_; }
    set {
      availableSpace_ = value;
    }
  }

  /// <summary>Field number for the "http_port" field.</summary>
  public const int HttpPortFieldNumber = 5;
  private string httpPort_ = "";
  /// <summary>
  /// host to interact with http file 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string HttpPort {
    get { return httpPort_; }
    set {
      httpPort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Server);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Server other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ZmqTcpPort != other.ZmqTcpPort) return false;
    if (Host != other.Host) return false;
    if (TotalSpace != other.TotalSpace) return false;
    if (AvailableSpace != other.AvailableSpace) return false;
    if (HttpPort != other.HttpPort) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ZmqTcpPort.Length != 0) hash ^= ZmqTcpPort.GetHashCode();
    if (Host.Length != 0) hash ^= Host.GetHashCode();
    if (TotalSpace != 0UL) hash ^= TotalSpace.GetHashCode();
    if (AvailableSpace != 0UL) hash ^= AvailableSpace.GetHashCode();
    if (HttpPort.Length != 0) hash ^= HttpPort.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ZmqTcpPort.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ZmqTcpPort);
    }
    if (Host.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Host);
    }
    if (TotalSpace != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(TotalSpace);
    }
    if (AvailableSpace != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(AvailableSpace);
    }
    if (HttpPort.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(HttpPort);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ZmqTcpPort.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ZmqTcpPort);
    }
    if (Host.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Host);
    }
    if (TotalSpace != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TotalSpace);
    }
    if (AvailableSpace != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AvailableSpace);
    }
    if (HttpPort.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HttpPort);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Server other) {
    if (other == null) {
      return;
    }
    if (other.ZmqTcpPort.Length != 0) {
      ZmqTcpPort = other.ZmqTcpPort;
    }
    if (other.Host.Length != 0) {
      Host = other.Host;
    }
    if (other.TotalSpace != 0UL) {
      TotalSpace = other.TotalSpace;
    }
    if (other.AvailableSpace != 0UL) {
      AvailableSpace = other.AvailableSpace;
    }
    if (other.HttpPort.Length != 0) {
      HttpPort = other.HttpPort;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ZmqTcpPort = input.ReadString();
          break;
        }
        case 18: {
          Host = input.ReadString();
          break;
        }
        case 24: {
          TotalSpace = input.ReadUInt64();
          break;
        }
        case 32: {
          AvailableSpace = input.ReadUInt64();
          break;
        }
        case 42: {
          HttpPort = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
